name: xkronus
favicon: null
layout_spectrum: 0.5016675307415426
typography_spectrum: 0.9376019146293402
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.7503198685590178
  lightness: 0.5878913982305676
  saturation: 0.734602760290727
  rhythmicContrast: 0.30183026753365993
purpose: []
